#!/bin/sh

while [ 1 ]; do
    /usr/bin/wifi_dump-tmpfs.bin "$@" &  # argument to be passed ?from where 
    trap "kill $!; rm -f $2; exit" INT TERM
    wait $!
    trap - INT TERM
    sleep 10
    echo "Restarting wifi_dump-tmpfs"
done
